server:
  port: 9090

##DB Connection
spring:
  mail:
    host: stmp.gmail.com
    port: 587
    username: eodus6480@gmail.com
    password: ichw krzf vhbm equi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smw?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: whiterilak12

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: 1234

logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace