server:
  port: 9090

##DB Connection
spring:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: 1234

logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace